@rootURL = http://localhost:3000
@apiUrl = {{rootURL}}/api/v1

###
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
    "fName": "sub",
    "lName": "baj",
    "phone": "768553",
    "email": "sub@gmail.com",
    "password": "1234",
    "role": "admin"
}

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "sub@gmail.com",
  "password": "1234"
}

### Get books publicly
GET {{apiUrl}}/books
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YkBnbWFpbC5jb20iLCJpYXQiOjE3NTYxNzE0NDIsImV4cCI6MTc1NjI1Nzg0Mn0.wE6xXzmKWsXwABbzcjCdAfuzYyrpXfUldFJIEppx_ek

### create book
POST {{apiUrl}}/books
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YkBnbWFpbC5jb20iLCJpYXQiOjE3NTYxNzE0NDIsImV4cCI6MTc1NjI1Nzg0Mn0.wE6xXzmKWsXwABbzcjCdAfuzYyrpXfUldFJIEppx_ek
Content-Type: application/json

{
  "title" : "book1",
  "author" : "book author",
  "thumbnail" : "https://wallpapercave.com/wp/rdYAno5.jpg",
  "isbn" : "12398222",
  "genre": "horror",
  "publishedYear" : 2020,
  "description" : "optional"
}